version: "3"

services:
  db:
    container_name: someapp_db
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ../../pgdata:/var/lib/postgresql/data
  api:
    container_name: someapp_api
    restart: always
    build:
      context: ../../someapp-backend
      dockerfile: Dockerfile.dev
    volumes:
      - ../../someapp-backend:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  app:
    container_name: someapp_app
    restart: always
    build:
      context: ../../someapp-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ../../someapp-frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - api
